cpmaddpackage(
  NAME tinygltf
  GITHUB_REPOSITORY syoyo/tinygltf
  GIT_TAG v2.9.7
  SYSTEM ON
  GIT_SHALLOW ON
  OPTIONS
    "TINYGLTF_HEADER_ONLY ON"
    "TINYGLTF_INSTALL OFF"
    "TINYGLTF_BUILD_LOADER_EXAMPLE OFF"
)
